### ISSUE TITLE
Importing types

### ISSUE THREAD

**Issue by m-tranter** [contensis/canvas#16]
I am not very experienced in TypeScript, but I had to do this to get the imports to work:

```
import { createRenderer } from '@contensis/canvas-html';
import type { Block } from '@contensis/canvas-html';
```

**Comment by nflatley-zengenti** [comment]
Hi @m-tranter,
Depending on how your project `tsconfig.json` and build is set up, you might need to use these "type-only" imports when importing type definitions in your code. We don't normally need to include them however there can be benefits to explicitly handle type imports this way.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export
https://typescript-eslint.io/blog/consistent-type-imports-and-exports-why-and-how/
