### ISSUE TITLE
Issue related to the React version

### ISSUE THREAD

**Issue by jonwelsh** [contensis/canvas#20]
## Bug/Issue
When adding canvas react to a project and setting up as per the example in npm, we run into an error. 
Error msg below:

<img width="783" alt="Screenshot 2024-07-12 at 16 12 42" src="https://github.com/user-attachments/assets/ada9dc6c-0640-4347-bcdf-d38540b11edd">

## Environment
- Remix with Vite
- Current canvas version:  ^1.1.0
- All other packages at latest versions

## Workaround
Our workaround for this issue was to add "type": "module" to the canvas-react package.json file in node_modules/@contensis. As seen below:

<img width="316" alt="Screenshot 2024-07-12 at 16 20 25" src="https://github.com/user-attachments/assets/d386acc6-20cb-4aaf-a8f0-7a5ca98f90bd">

**Comment by nflatley-zengenti** [comment]
Hi @jonwelsh,
As previously discussed we found that testing v1.0.4 of the canvas-react package did not have this issue.
I have reverted the change that went into v1.0.5 and we have found another resolution to the original issue that v1.0.5 was attempting to solve. It affects some older React projects building with webpack v4.

The change will go into the next package release and we would encourage you to keep this package up to date with your other project package dependencies as you would normally do.
Kind regards,
Neil
